sudo: required
services:
    - docker

before_install:
    - docker build -t ishaan99ohri/docker-react -f Dockerfile.dev .

script:
    - docker run ishaan99ohri/docker-react npm run test -- --coverage